version: "3.0"

# --- volumes
volumes:
  mongodb:
  elasticsearch:


# --- services
services:
  # example app to be monitored
  example_app:
    container_name: example-app
    build: ./expressjs_custom_spans
    depends_on:
      - mongodb
    ports:
      - "5000:5000"

  # mongodb
  mongodb:
    container_name: mongodb
    image: mongo:4.2
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb:/data/db


  # elasticsearch
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    ports:
      - 9200:9200
    environment:
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      # - xpack.security.authc.api_key.enabled=true
      - "discovery.type=single-node"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  # elastic apm server
  apm:
    container_name: elastic-apm
    image: docker.elastic.co/apm/apm-server:7.10.2
    depends_on:
      - elasticsearch
    ports:
      - 8200:8200
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=kibana:5601
        -E setup.kibana.host=kibana:5601
        -E setup.template.settings.index.number_of_replicas=0
        -E output.elasticsearch.hosts=["elasticsearch:9200"]

  # kibana
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.10.2
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
